pipeline {
    agent any

    tools {
        maven 'PaikallinenMaven'
        git 'Default'
    }

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_REPO = "topiahola/jenkins_docker_repo"
        DOCKERHUB_CREDENTIALS_ID = "dockehub_pat"
        DOCKER_IMAGE_TAG = "week1_localization"
        PATH_TO_DOCKER_EXE = "path_to_docker_exe"
    }

    stages {
/*

         stage('Checkout with SSH') {
            steps {
                git branch: 'main', url: 'git@github.com:/Quuikz/OTP.git', credentialsId:'ssh TopiAhola'
            }
        } */


         stage('Checkout with git tool') {
            steps {
                git 'https://github.com/TopiAhola/otp2_assignments.git'
            }
        }

        stage('Runt tests') {
            steps {
                bat '''
                cd ./week1_localization
                mvn clean test
                '''
            }
        }

        stage('Code Coverage') {
            steps {
                bat '''
                cd ./week1_localization
                 mvn jacoco:report
                 '''
            }
        }

        stage('Publish Test Results') {
            steps {
                junit './week1_localization/target/surefire-reports/*.xml'
            }
        }

        /*
        stage('Publish Coverage Report') {
            steps {
                recordCoverage(
                    tools: [[parser: 'JACOCO', pattern: '**//* target/site/jacoco/jacoco.xml']]
                )
            }
        }
        */

        stage('Publish Coverage Report with Jacoco plugin') {
            steps {
                jacoco()
            }
        }

        stage('Start Docker') {
            steps {
                bat "${PATH_TO_DOCKER_EXE}"
            }
        }

        stage('Build Docker Image') {
            steps {
                //build from dockerfile in server
                script {
                    dir ('./week1_localization/') {
                        //name repo:otp:server
                        docker.build("${DOCKERHUB_REPO}:")
                    }
                }
            }
        }

        stage('Build Docker Image for APPLICATION') {
            steps {
                //build from dockerfile in application
                script {
                    dir ('./application/') {
                        //name repo:otp_application
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        //docker push topiahola/jenkins_docker_repo:${DOCKER_IMAGE_TAG}
         stage ('push docker image to dockerhub'){
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }



    }
}
