pipeline {
    agent any

    tools {
        maven 'PaikallinenMaven'
        git 'Default'
    }

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_REPO = "topiahola/jenkins_docker_repo"
        DOCKERHUB_CREDENTIALS_ID = "dockehub_pat"
        BUILD_IMAGE_NAME = "week1"
        //DOCKER_IMAGE_TAG = ""

    }

    stages {
/*
         //use ssh type uri and credentials (normal URL: 'https://github.com/Quuikz/OTP')
         stage('Checkout with SSH') {
            steps {
                git branch: 'main', url: 'git@github.com:/Quuikz/OTP.git', credentialsId:'ssh TopiAhola'
            }
        } */


         stage('Checkout with git tool') {
            steps {
                git 'https://github.com/TopiAhola/ .git'
            }
        }


        stage('Runt tests') {
            steps {
                bat '''
                cd ./week1_localization
                mvn clean test
                '''
            }
        }

        stage('Code Coverage') {
            steps {
                bat '''
                cd ./week1_localization
                 mvn jacoco:report
                 '''
            }
        }

        stage('Publish Test Results') {
            steps {
                junit '*/target/surefire-reports/*.xml'
            }
        }


        /*
        stage('Publish Coverage Report') {
            steps {
                recordCoverage(
                    tools: [[parser: 'JACOCO', pattern: '**//* target/site/jacoco/jacoco.xml']]
                )
            }
        }
        */

        stage('Publish Coverage Report with Jacoco plugin') {
            steps {
                jacoco()
            }
        }

        stage('Build Docker Image') {
            steps {
                //build from dockerfile in server
                script {
                    dir ('./week1_localization/') {
                        //name repo:otp:server
                        docker.build("${DOCKERHUB_REPO}:otp_server")
                    }
                }
            }
        }

        stage('Build Docker Image for APPLICATION') {
            steps {
                //build from dockerfile in application
                script {
                    dir ('./application/') {
                        //name repo:otp_application
                        docker.build("${DOCKERHUB_REPO}:otp_application")
                    }
                }
            }
        }



        //docker push topiahola/jenkins_docker_repo:tagname
         stage ('push docker image to dockerhub'){
            steps {
                script {
                    //käyttää dockeria ei-oletus repositiolla
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:otp_server").push()
                        docker.image("${DOCKERHUB_REPO}:otp_application").push()
                    }
                }
            }
        }



    }
}
