pipeline {
    agent any

    tools {
        maven 'Default'
        git 'Default'
    }

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_REPO = "topiahola/jenkins_docker_repo"
        DOCKERHUB_CREDENTIALS_ID = "dockehub_pat"
        DOCKER_IMAGE_TAG = "week2_localization"
        PATH_TO_DOCKER_EXE = "path_to_docker_exe"

        REPO_WORKING_DIRECTORY = "./week2_localization"
    }

    stages {
         stage('Checkout with git tool') {
            steps {
                git 'https://github.com/TopiAhola/otp2_assignments.git'
            }
        }

        stage('Run tests') {
            steps {
                bat """
                cd ${REPO_WORKING_DIRECTORY}
                mvn clean test
                """
            }
        }

        stage('Code Coverage') {
            steps {
                bat """
                cd ${REPO_WORKING_DIRECTORY}
                 mvn jacoco:report
                 """
            }
        }

/*         stage('Publish Test Results') {
            steps {
                junit '*//* target/surefire-reports *//*.xml'
            }
        }

        stage('Publish Coverage Report with Coverage plugin') {
            steps {
                recordCoverage(
                    tools: [[parser: 'JACOCO', pattern: '**//*  *//* target/site/jacoco/jacoco.xml']]
                )
            }
        } */


/*         stage('Publish Coverage Report with Jacoco plugin') {
            steps {
                jacoco()
            }
        } */

 /*        stage('Package .jar') {
            steps {
                bat """
                cd ${REPO_WORKING_DIRECTORY}
                 mvn package
                 """
            }
        } */

        stage('Build Docker Image with Dockerfile') {
            steps {
                //build from dockerfile
                script {
                    dir ("${REPO_WORKING_DIRECTORY}") {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        //docker push topiahola/jenkins_docker_repo:${DOCKER_IMAGE_TAG}
         stage ('push docker image to dockerhub'){
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }

    }
}
